### ISSUE TITLE
Allow users to change account when logging in

### ISSUE THREAD

**Issue by Nomorewine** [kakao/kakao_flutter_sdk#20]
Hi. 
I have problem logging out. 
I have no error to show. 

```
    KakaoContext.clientId = "native app key"; // native app key

    String authCode = await AuthCodeClient.instance.request();

    var token = await AuthApi.instance.issueAccessToken(authCode);
    AccessTokenStore.instance.toStore(token);

    UserApi _userApi = UserApi.instance;
   
    await _userApi.logout();
    await AccessTokenStore.instance.clear();

```
after I tap logout the code above is called but then when I tap login, kakao will automatically log me in. without asking for my credentials. 
I'm trying to ask for login credentials every time [Kakao login] button is tapped. Thank you for the library.

==== EDIT
It appears that login persists due to default browser's cache...
Once I've cleared the cache manually, kakao asked for credentials.

**Comment by CoderSpinoza** [comment]
Yes, this is the expected behavior as of now. Using default browser has upsides and down-sides.

I believe Kakao is planning to land users on a page (even if they are logged in to Kakao Account website) where users can confirm their accounts and log in with a different account. Until then, this won't have a clear fix..

I will rename this issue appropriately so that I wouldn't have to close this and allow developers to follow up on this issue. Thanks for reporting :)

**Comment by Nomorewine** [comment]
I see. Thank you for quick response :)

**Comment by CoderSpinoza** [comment]
@Nomorewine This issue has been finally fixed :)

<img width="559" alt="KakaoTalk_Photo_2020-10-16-15-24-34" src="https://user-images.githubusercontent.com/1980943/96220620-02358280-0fc4-11eb-8f8f-a30ccd04d7c0.png">

Above describes how users are first landed on a confirm page where they can proceed or change account before login.
.
